name = "Packwiz Yea v 1"
author = "Beedit"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "501578c2d57c0443d95e594197b3795f6bd31080d28fd8ec2c6082ae1d32b152"

[versions]
minecraft = "1.20.1"
quilt = "0.22.1-beta.4"
